
package com.btpn.ws.mdw.btpnfesaccountequation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BtpnFesAccountEquation_PortType", targetNamespace = "http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesAccountEquation")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BtpnFesAccountEquationPortType {

    /**
     * 
     * @param requestCLA
     * @return
     *     returns com.btpn.ws.mdw.btpnfesaccountequation.CloseCustomerAccountRes
     */
    @WebMethod(action = "com_btpn_fes_ws_provider_BtpnFesAccountEquation_Binder_closeCustomerAccount")
    @WebResult(name = "ResponseCLA", targetNamespace = "")
    @RequestWrapper(localName = "closeCustomerAccount", targetNamespace = "http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesAccountEquation", className = "com.btpn.ws.mdw.btpnfesaccountequation.CloseCustomerAccount")
    @ResponseWrapper(localName = "closeCustomerAccountResponse", targetNamespace = "http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesAccountEquation", className = "com.btpn.ws.mdw.btpnfesaccountequation.CloseCustomerAccountResponse")
    public CloseCustomerAccountRes closeCustomerAccount(
        @WebParam(name = "RequestCLA", targetNamespace = "")
        CloseCustomerAccountReq requestCLA);
}