
package com.btpn.ws.diasoft.corews;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "COREWSSERVICE", targetNamespace = "http://support.diasoft.ru", wsdlLocation = "http://10.1.77.84:8080/corews/corews?wsdl")
public class COREWSSERVICE
    extends Service
{

    private final static URL COREWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException COREWSSERVICE_EXCEPTION;
    private final static QName COREWSSERVICE_QNAME = new QName("http://support.diasoft.ru", "COREWSSERVICE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.77.84:8080/corews/corews?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COREWSSERVICE_WSDL_LOCATION = url;
        COREWSSERVICE_EXCEPTION = e;
    }

    public COREWSSERVICE() {
        super(__getWsdlLocation(), COREWSSERVICE_QNAME);
    }

    public COREWSSERVICE(WebServiceFeature... features) {
        super(__getWsdlLocation(), COREWSSERVICE_QNAME, features);
    }

    public COREWSSERVICE(URL wsdlLocation) {
        super(wsdlLocation, COREWSSERVICE_QNAME);
    }

    public COREWSSERVICE(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COREWSSERVICE_QNAME, features);
    }

    public COREWSSERVICE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public COREWSSERVICE(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns COREWSPORTTYPE
     */
    @WebEndpoint(name = "COREWSPORT")
    public COREWSPORTTYPE getCOREWSPORT() {
        return super.getPort(new QName("http://support.diasoft.ru", "COREWSPORT"), COREWSPORTTYPE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns COREWSPORTTYPE
     */
    @WebEndpoint(name = "COREWSPORT")
    public COREWSPORTTYPE getCOREWSPORT(WebServiceFeature... features) {
        return super.getPort(new QName("http://support.diasoft.ru", "COREWSPORT"), COREWSPORTTYPE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COREWSSERVICE_EXCEPTION!= null) {
            throw COREWSSERVICE_EXCEPTION;
        }
        return COREWSSERVICE_WSDL_LOCATION;
    }

}
