
package com.btpn.ws.diasoft.frontws2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FRONTWS2SERVICE", targetNamespace = "http://support.diasoft.ru", wsdlLocation = "http://10.1.77.85:8090/frontws2/frontws2?wsdl")
public class FRONTWS2SERVICE
    extends Service
{

    private final static URL FRONTWS2SERVICE_WSDL_LOCATION;
    private final static WebServiceException FRONTWS2SERVICE_EXCEPTION;
    private final static QName FRONTWS2SERVICE_QNAME = new QName("http://support.diasoft.ru", "FRONTWS2SERVICE");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.77.85:8090/frontws2/frontws2?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FRONTWS2SERVICE_WSDL_LOCATION = url;
        FRONTWS2SERVICE_EXCEPTION = e;
    }

    public FRONTWS2SERVICE() {
        super(__getWsdlLocation(), FRONTWS2SERVICE_QNAME);
    }

    public FRONTWS2SERVICE(WebServiceFeature... features) {
        super(__getWsdlLocation(), FRONTWS2SERVICE_QNAME, features);
    }

    public FRONTWS2SERVICE(URL wsdlLocation) {
        super(wsdlLocation, FRONTWS2SERVICE_QNAME);
    }

    public FRONTWS2SERVICE(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FRONTWS2SERVICE_QNAME, features);
    }

    public FRONTWS2SERVICE(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FRONTWS2SERVICE(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FRONTWS2PORTTYPE
     */
    @WebEndpoint(name = "FRONTWS2PORT")
    public FRONTWS2PORTTYPE getFRONTWS2PORT() {
        return super.getPort(new QName("http://support.diasoft.ru", "FRONTWS2PORT"), FRONTWS2PORTTYPE.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FRONTWS2PORTTYPE
     */
    @WebEndpoint(name = "FRONTWS2PORT")
    public FRONTWS2PORTTYPE getFRONTWS2PORT(WebServiceFeature... features) {
        return super.getPort(new QName("http://support.diasoft.ru", "FRONTWS2PORT"), FRONTWS2PORTTYPE.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FRONTWS2SERVICE_EXCEPTION!= null) {
            throw FRONTWS2SERVICE_EXCEPTION;
        }
        return FRONTWS2SERVICE_WSDL_LOCATION;
    }

}
