
package com.btpn.ws.diasoft.frontws2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FRONTWS2PORTTYPE", targetNamespace = "http://support.diasoft.ru")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FRONTWS2PORTTYPE {


    /**
     * 
     * @param commanddata
     * @param commandtext
     * @return
     *     returns java.lang.String
     * @throws DSCALLFAULT_Exception
     */
    @WebMethod(operationName = "DSCALL")
    @WebResult(name = "commandresult", targetNamespace = "http://support.diasoft.ru")
    @RequestWrapper(localName = "DSCALL", targetNamespace = "http://support.diasoft.ru", className = "com.btpn.ws.diasoft.frontws2.DSCALL")
    @ResponseWrapper(localName = "DSCALLRESPONSE", targetNamespace = "http://support.diasoft.ru", className = "com.btpn.ws.diasoft.frontws2.DSCALLRESPONSE")
    public String dscall(
        @WebParam(name = "commandtext", targetNamespace = "http://support.diasoft.ru")
        String commandtext,
        @WebParam(name = "commanddata", targetNamespace = "http://support.diasoft.ru")
        String commanddata)
        throws DSCALLFAULT_Exception
    ;


}
