
package com.btpn.ws.mdw.btpnfescustomerequation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BtpnFesCustomerEquation_PortType", targetNamespace = "http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesCustomerEquation")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BtpnFesCustomerEquationPortType {

    /**
     * 
     * @param addressEnquiryReq
     * @return
     *     returns com.btpn.ws.mdw.btpnfescustomerequation.AddressEnquiryResp
     */
    @WebMethod(action = "com_btpn_fes_ws_provider_BtpnFesCustomerEquation_Binder_addressEnquiry")
    @WebResult(name = "addressEnquiryResp", targetNamespace = "")
    @RequestWrapper(localName = "addressEnquiry", targetNamespace = "http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesCustomerEquation", className = "com.btpn.ws.mdw.btpnfescustomerequation.AddressEnquiry")
    @ResponseWrapper(localName = "addressEnquiryResponse", targetNamespace = "http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesCustomerEquation", className = "com.btpn.ws.mdw.btpnfescustomerequation.AddressEnquiryResponse")
    public AddressEnquiryResp addressEnquiry(
        @WebParam(name = "addressEnquiryReq", targetNamespace = "")
        AddressEnquiryReq addressEnquiryReq);

}
