
package com.btpn.ws.mdw.btpnfescustomerequation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "com.btpn.fes.ws.provider.BtpnFesCustomerEquation", targetNamespace = "http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesCustomerEquation", wsdlLocation = "http://appmdwdev03.dev.corp.btpn.co.id:5555/ws/com.btpn.fes.ws.provider:BtpnFesCustomerEquation?WSDL")
public class ComBtpnFesWsProviderBtpnFesCustomerEquation
    extends Service
{

    private final static URL COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_WSDL_LOCATION;
    private final static WebServiceException COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_EXCEPTION;
    private final static QName COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_QNAME = new QName("http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesCustomerEquation", "com.btpn.fes.ws.provider.BtpnFesCustomerEquation");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://appmdwdev03.dev.corp.btpn.co.id:5555/ws/com.btpn.fes.ws.provider:BtpnFesCustomerEquation?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_WSDL_LOCATION = url;
        COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_EXCEPTION = e;
    }

    public ComBtpnFesWsProviderBtpnFesCustomerEquation() {
        super(__getWsdlLocation(), COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_QNAME);
    }

    public ComBtpnFesWsProviderBtpnFesCustomerEquation(WebServiceFeature... features) {
        super(__getWsdlLocation(), COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_QNAME, features);
    }

    public ComBtpnFesWsProviderBtpnFesCustomerEquation(URL wsdlLocation) {
        super(wsdlLocation, COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_QNAME);
    }

    public ComBtpnFesWsProviderBtpnFesCustomerEquation(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_QNAME, features);
    }

    public ComBtpnFesWsProviderBtpnFesCustomerEquation(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComBtpnFesWsProviderBtpnFesCustomerEquation(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BtpnFesCustomerEquationPortType
     */
    @WebEndpoint(name = "com_btpn_fes_ws_provider_BtpnFesCustomerEquation_Port")
    public BtpnFesCustomerEquationPortType getComBtpnFesWsProviderBtpnFesCustomerEquationPort() {
        return super.getPort(new QName("http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesCustomerEquation", "com_btpn_fes_ws_provider_BtpnFesCustomerEquation_Port"), BtpnFesCustomerEquationPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BtpnFesCustomerEquationPortType
     */
    @WebEndpoint(name = "com_btpn_fes_ws_provider_BtpnFesCustomerEquation_Port")
    public BtpnFesCustomerEquationPortType getComBtpnFesWsProviderBtpnFesCustomerEquationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://APPMDWDEV03.dev.corp.btpn.co.id/com.btpn.fes.ws.provider:BtpnFesCustomerEquation", "com_btpn_fes_ws_provider_BtpnFesCustomerEquation_Port"), BtpnFesCustomerEquationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_EXCEPTION!= null) {
            throw COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_EXCEPTION;
        }
        return COMBTPNFESWSPROVIDERBTPNFESCUSTOMEREQUATION_WSDL_LOCATION;
    }

}
